[package]
name = "ripasso"
description = "A password manager that uses the file format of the standard unix password manager 'pass'"
repository = "https://github.com/cortex/ripasso/"
keywords = ["password-manager", "pass"]
version = "0.7.0-alpha"
authors = ["Joakim Lundborg <joakim.lundborg@gmail.com", "Alexander Kjäll <alexander.kjall@gmail.com>"]
license = "GPL-3.0-only"
edition = '2021'

[dependencies]
arboard = "3.2.1"
glob = "0.3.1"
gpgme = "0.11.0"
chrono = { version = "0.4", default_features = false, features = ["clock"] }
git2 = "0.18.1"
rand = "0.8.5"
whoami = "1.4.1"
toml = "0.8.2"
reqwest = { version = "0.11.22", features = ["blocking"] }
hex = "0.4.3"
totp-rs = { version = "5.3.0", features = ["otpauth"] }
sequoia-openpgp = "1.16.1"
anyhow = "1.0.75"
sequoia-ipc = "0.30.1"
base64 = "0.21.4"
sha2 = "0.10.8"
sha1 = "0.10.6"
hmac = "0.12.1"
zeroize = { version = "1.7.0", features = ["zeroize_derive", "alloc"] }

[dependencies.config]
version = "0.11.0"
default-features = false
features = ["toml"]

[dev-dependencies]
tempfile = "3.8.0"
flate2 = "1.0.27"
tar = "0.4.40"
criterion = "0.5.1"

[workspace]

members = [
    "gtk", "cursive"
]

[[bench]]
name = "library_benchmark"
harness = false

[profile.release]
lto = true
codegen-units = 1
strip = true
debug = false
